remote_theme: konstantin-morenko/just-the-docs

title: Английский язык
description: Коллекция материалов по английскому языку от Константина Моренко

aux_links:
  "Константин Моренко":
    - "https://konstantin-morenko.ru"

color_scheme: light_blue
